Promise after reject/resolve â€“ unchanged

```javascript
 1| let promise = new Promise((resolve, reject) => {
 2|   setTimeout(() => resolve("result"), 1000);
 3|   setTimeout(() => reject(new Error("ignored")), 2000);
 4| });
 5| 
 6| promise
 7|   .then(
 8|     result => alert("Fulfilled: " + result),//call
 9|     error => alert("Rejected: " + error) //not call
10|   );
```